services:
  - type: worker
    name: manga-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manga_bot_comick.py
    envVars:
      - key: BOT_TOKEN
        sync: false
